-- INSERT INTO mpa_ratings (name)
-- values ('G'),
--        ('PG'),
--        ('PG-13'),
--        ('R'),
--        ('NC-17');
--
-- INSERT INTO genres (name)
-- values ('Комедия'),
--        ('Драма'),
--        ('Мультфильм'),
--        ('Триллер'),
--        ('Документальный'),
--        ('Боевик');