CREATE TABLE IF NOT EXISTS mpa_rating
(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    film_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40) NOT NULL,
    description VARCHAR(200),
    rating_id   INTEGER REFERENCES mpa_rating (rating_id),
    release     TIMESTAMP CHECK (release >= '1895-12-28'),
    duration    INTEGER     NOT NULL CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  INTEGER REFERENCES film (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS user_data
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(40) NOT NULL,
    login    VARCHAR(40) CHECK (regexp_like(login, '^\S+$')),
    email    VARCHAR     NOT NULL,
    birthday TIMESTAMP   NOT NULL
);

CREATE TABLE IF NOT EXISTS like_film
(
    film_id INTEGER REFERENCES film (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES user_data (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS follow
(
    target_id   INTEGER REFERENCES user_data (user_id) ON DELETE CASCADE,
    follower_id INTEGER REFERENCES user_data (user_id) ON DELETE CASCADE,
    approved    BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (target_id, follower_id)
);

CREATE TABLE IF NOT EXISTS review
(
	review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content     text NOT NULL,
    user_id     INTEGER REFERENCES user_data (user_id) ON DELETE CASCADE,
    film_id     INTEGER REFERENCES film (film_id) ON DELETE CASCADE,
    is_positive BOOLEAN not null DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS like_review
(
	user_id     INTEGER REFERENCES user_data (user_id) ON DELETE CASCADE,
    review_id   INTEGER REFERENCES review (review_id) ON DELETE CASCADE,
    usefull     BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (user_id, review_id)
);
